[package]
name = "beany"
version = "0.1.0"
authors = ["Sam Macaluso <sam@macalu.so>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
