[package]
name = "beany"
version = "0.1.0"
authors = ["Sam Macaluso <sam@macalu.so>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/oonis/Beany"
license = "MIT"

[dependencies]
